name: Deploy X Website

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: production-deploy
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Deploy website via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.FTP_PORT }}
          server-dir: ./
          local-dir: ./
          dry-run: false
          security: strict
          log-level: standard

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
            **/aryawebdesign.zip
            **/.DS_Store
            **/node_modules/**
